# Generated by Django 4.0 on 2022-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.CharField(default='без темы', max_length=256),
        ),
    ]
