# Generated by Django 4.0 on 2022-06-17 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_post_comment_article_alter_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislike_count',
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 11, 29, 48, 540226, tzinfo=utc)),
        ),
    ]
