# Generated by Django 4.0 on 2022-06-24 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_pub_date_alter_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 17, 4, 37, 967350, tzinfo=utc)),
        ),
    ]
